language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bower install
  - npm install bitcore-lib
  - npm install
after_script:
  - gulp coveralls
