language: node_js
node_js:
  - '8'
install:
  - npm install
  - bower install
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc\
  - npm install -g bower
  - npm install -g grunt-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm run lint
after_script:
  - gulp coveralls
